name: rabenkorb
description: An app to manage your shopping
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  path_provider: ^2.1.2
  path: 1.9.0
  watch_it: ^1.4.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  intl: 0.18.1
  package_info_plus: ^6.0.0
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.4
  codenic_logger: ^4.0.1
  device_info_plus: ^10.1.0
  mongo_dart: ^0.10.2
  permission_handler: ^11.3.1
  file_picker: ^8.0.3
  sqlite3_flutter_libs: ^0.5.21
  drag_and_drop_lists: ^0.3.3
  dropdown_search: ^5.0.6
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.15.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
