name: rabenkorb
description: An app to manage your shopping
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.19+1
  path_provider: ^2.1.2
  path: 1.9.0
  watch_it: ^1.4.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.15.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
