import 'package:rabenkorb/database/database.dart';

Map<String, SortRule> exampleSortRules = {
  "Famila": const SortRule(id: 1, name: "Famila"),
  "Rewe": const SortRule(id: 2, name: "Rewe"),
};

List<SortOrder> exampleSortOrdersRuleOne = [
  SortOrder(categoryId: exampleCategories["Alkohol"]!.id, sortOrder: 1, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["ObstGemüse"]!.id, sortOrder: 2, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Vegan"]!.id, sortOrder: 3, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["FrischeTheke"]!.id, sortOrder: 4, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["KühlthekeTeil1"]!.id, sortOrder: 5, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Backwaren"]!.id, sortOrder: 6, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["KühlthekeTeil2"]!.id, sortOrder: 7, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Heißgetränke"]!.id, sortOrder: 8, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["MilchSahne"]!.id, sortOrder: 9, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Trockenprodukte"]!.id, sortOrder: 10, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Tomatenzeug"]!.id, sortOrder: 11, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Teigwaren"]!.id, sortOrder: 12, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Konserven"]!.id, sortOrder: 13, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Vorratsschrank"]!.id, sortOrder: 14, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Backzutaten"]!.id, sortOrder: 15, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Snacks"]!.id, sortOrder: 16, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Haushalt"]!.id, sortOrder: 17, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Drogerie"]!.id, sortOrder: 18, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Getränke"]!.id, sortOrder: 19, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Tiefkühl"]!.id, sortOrder: 20, ruleId: exampleSortRules["Famila"]!.id),
  SortOrder(categoryId: exampleCategories["Gewürze"]!.id, sortOrder: 21, ruleId: exampleSortRules["Famila"]!.id),
];

List<SortOrder> exampleSortOrdersRuleTwo = [
  SortOrder(categoryId: exampleCategories["Alkohol"]!.id, sortOrder: 1, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["ObstGemüse"]!.id, sortOrder: 2, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Vegan"]!.id, sortOrder: 3, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["FrischeTheke"]!.id, sortOrder: 4, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["KühlthekeTeil1"]!.id, sortOrder: 5, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Backwaren"]!.id, sortOrder: 6, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["KühlthekeTeil2"]!.id, sortOrder: 7, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Heißgetränke"]!.id, sortOrder: 8, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["MilchSahne"]!.id, sortOrder: 9, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Trockenprodukte"]!.id, sortOrder: 10, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Tomatenzeug"]!.id, sortOrder: 11, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Teigwaren"]!.id, sortOrder: 12, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Konserven"]!.id, sortOrder: 13, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Vorratsschrank"]!.id, sortOrder: 14, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Backzutaten"]!.id, sortOrder: 15, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Snacks"]!.id, sortOrder: 16, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Haushalt"]!.id, sortOrder: 17, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Drogerie"]!.id, sortOrder: 18, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Getränke"]!.id, sortOrder: 19, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Tiefkühl"]!.id, sortOrder: 20, ruleId: exampleSortRules["Rewe"]!.id),
  SortOrder(categoryId: exampleCategories["Gewürze"]!.id, sortOrder: 21, ruleId: exampleSortRules["Rewe"]!.id),
];

Map<String, ItemCategory> exampleCategories = {
  "Alkohol": const ItemCategory(id: 1, name: "Alkohol"),
  "ObstGemüse": const ItemCategory(id: 2, name: "Obst & Gemüse"),
  "Vegan": const ItemCategory(id: 3, name: "Vegan"),
  "FrischeTheke": const ItemCategory(id: 4, name: "Frische Theke"),
  "KühlthekeTeil1": const ItemCategory(id: 5, name: "Kühltheke Teil 1"),
  "Backwaren": const ItemCategory(id: 6, name: "Backwaren"),
  "KühlthekeTeil2": const ItemCategory(id: 7, name: "Kühltheke Teil 2"),
  "Heißgetränke": const ItemCategory(id: 8, name: "Heißgetränke"),
  "MilchSahne": const ItemCategory(id: 9, name: "Milch/Sahne"),
  "Trockenprodukte": const ItemCategory(id: 10, name: "Trockenprodukte"),
  "Tomatenzeug": const ItemCategory(id: 11, name: "Tomatenzeug"),
  "Teigwaren": const ItemCategory(id: 12, name: "Teigwaren"),
  "Konserven": const ItemCategory(id: 13, name: "Konserven"),
  "Vorratsschrank": const ItemCategory(id: 14, name: "Vorratsschrank"),
  "Backzutaten": const ItemCategory(id: 15, name: "Backzutaten"),
  "Snacks": const ItemCategory(id: 16, name: "Snacks"),
  "Haushalt": const ItemCategory(id: 17, name: "Haushalt"),
  "Drogerie": const ItemCategory(id: 18, name: "Drogerie"),
  "Getränke": const ItemCategory(id: 19, name: "Getränke"),
  "Tiefkühl": const ItemCategory(id: 20, name: "Tiefkühl"),
  "Gewürze": const ItemCategory(id: 21, name: "Gewürze"),
};

Map<String, ItemUnit> exampleUnits = {
  "g": const ItemUnit(id: 1, name: "g"),
  "kg": const ItemUnit(id: 2, name: "kg"),
  "l": const ItemUnit(id: 3, name: "l"),
  "mg": const ItemUnit(id: 4, name: "mg"),
  "ml": const ItemUnit(id: 5, name: "ml"),
  "Stange": const ItemUnit(id: 6, name: "Stange"),
  "Stück": const ItemUnit(id: 7, name: "Stück"),
  "Tl": const ItemUnit(id: 8, name: "Tl"),
  "EL": const ItemUnit(id: 9, name: "EL"),
  "Glas": const ItemUnit(id: 10, name: "Glas"),
  "Dose": const ItemUnit(id: 11, name: "Dose"),
};

Map<String, TemplateLibrary> exampleLibraries = {
  "Library One": const TemplateLibrary(id: 1, name: "Library One"),
};

Map<String, VariantKey> exampleVariantKeys = {
  "Key 1": const VariantKey(id: 1),
};

List<ItemTemplate> exampleItemTemplates = [
  ItemTemplate(id: 1, name: "Kartoffelwedges", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 2, name: "Aufschnitt", category: exampleCategories["KühlthekeTeil1"]?.id, library: 1),
  ItemTemplate(id: 3, name: "Baldrian", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 4, name: "Brötchen ", category: exampleCategories["Backwaren"]?.id, library: 1),
  ItemTemplate(id: 5, name: "Butter", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 6, name: "Deo", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 7, name: "Desinfektionsmittel ", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 8, name: "Duschgel ", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 9, name: "Eistee", category: exampleCategories["Getränke"]?.id, library: 1),
  ItemTemplate(id: 10, name: "Getränke ", category: exampleCategories["Getränke"]?.id, library: 1),
  ItemTemplate(id: 11, name: "Giotto", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 12, name: "Handseife ", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 13, name: "Joghurt / Dessert", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 14, name: "Knoblauch", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 15, name: "Küchenrolle ", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 16, name: "Mikado", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 17, name: "Milch", category: exampleCategories["MilchSahen"]?.id, library: 1),
  ItemTemplate(id: 18, name: "Milchschnitte", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 19, name: "Müllbeutel, 35l", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 20, name: "Müsli", category: exampleCategories["Trockenprodukte"]?.id, library: 1),
  ItemTemplate(id: 21, name: "Nudeln", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 22, name: "Pickup", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 23, name: "Salz", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 24, name: "Schokoküsse", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 25, name: "Schwarzbiersenf ", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 26, name: "Snacks", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 27, name: "TK ", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 28, name: "WC-Papier", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 29, name: "Zahnbürste", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 30, name: "Zahnpasta", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 31, name: "True Fruits", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 32, name: "Schinken", category: exampleCategories["KühlthekeTeil1"]?.id, library: 1),
  ItemTemplate(id: 33, name: "Champignons", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 34, name: "Lauch", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 35, name: "Schlagsahne", category: exampleCategories["MilchSahen"]?.id, library: 1),
  ItemTemplate(id: 36, name: "Petersilie", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 37, name: "Gewürze", category: exampleCategories["Gewürze"]?.id, library: 1),
  ItemTemplate(id: 38, name: "Brombeeren", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 39, name: "Griechischer Joghurt", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 40, name: "Heidelbeeren", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 41, name: "Bananen", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 42, name: "Orangen", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 43, name: "Kartoffeln, festkochend", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 44, name: "Paprika, Rot", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 45, name: "Rote Zwiebel", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 46, name: "Creme Fraiche (30%)", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 47, name: "Joghurt", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 48, name: "Waschmittel", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 49, name: "Kaffee", category: exampleCategories["Heißgetränke"]?.id, library: 1),
  ItemTemplate(id: 50, name: "Schnelltest", category: null, library: 1),
  ItemTemplate(id: 51, name: "Kartoffeln, vorwiegend festkochend", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 52, name: "Selter", category: exampleCategories["Getränke"]?.id, library: 1),
  ItemTemplate(id: 53, name: "Zucker", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 54, name: "Magnesium", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 55, name: "Tagliatelle", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 56, name: "Käse (Rebekka)", category: exampleCategories["KühlthekeTeil1"]?.id, library: 1),
  ItemTemplate(id: 57, name: "Möhren", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 58, name: "Haselnüsse, gemahlen", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 59, name: "Mandeln, gemahlen", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 60, name: "Eier", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 61, name: "Zucker", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 62, name: "Mehl", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 63, name: "Backpulver", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 64, name: "Paniermehl", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 65, name: "Frühlingszwiebeln", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 66, name: "Erbsen", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 67, name: "Wasserfilter", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 68, name: "Äpfel", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 69, name: "Öl", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 70, name: "Haselnussglasur", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 71, name: "Rinderhack", category: exampleCategories["KühlthekeTeil1"]?.id, library: 1),
  ItemTemplate(id: 72, name: "Reis", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 73, name: "Paprika, Gelb", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 74, name: "Pak Choi", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 75, name: "Sojasauce", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 76, name: "Vodka", category: exampleCategories["Alkohol"]?.id, library: 1),
  ItemTemplate(id: 78, name: "Kohlrabi", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 79, name: "Schmand", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 82, name: "Eier", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 83, name: "Mozzarella", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 84, name: "Käse, gerieben", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 85, name: "Cold Tea", category: exampleCategories["Heißgetränke"]?.id, library: 1),
  ItemTemplate(id: 86, name: "Rahmspinat", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 87, name: "Karotten", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 88, name: "Zwiebel", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 89, name: "Kräuterfrischkäse", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 90, name: "Passierte Tomaten", category: exampleCategories["Tomatenzeug"]?.id, library: 1),
  ItemTemplate(id: 91, name: "Süße Sahne", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 92, name: "Lasagneplatten", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 93, name: "Mund-Wundgel", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 94, name: "Pickers Italian Pops", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 95, name: "Kuchenbackmischung", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 96, name: "Backpapier", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 97, name: "Sesamöl", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 98, name: "Brokkoli", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 99, name: "Erdnussbutter", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 100, name: "Spaghetti", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 101, name: "Obst (Bekka)", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 102, name: "Schwämme", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 103, name: "Pizza, Tomate-Mozerella || Funghi (Dr. Oetker, dünn)", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 104, name: "Pizza", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 105, name: "Gemüsebällchen", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 107, name: "Harris Baguette Brötchen", category: exampleCategories["Backwaren"]?.id, library: 1),
  ItemTemplate(id: 108, name: "Slipeinlagen", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 110, name: "Toilettenpapier", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 111, name: "Eis", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 112, name: "Nougatcreme", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 113, name: "Kräuterfrischkäse", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 114, name: "Passierte Tomaten", category: exampleCategories["Tomatenzeug"]?.id, library: 1),
  ItemTemplate(id: 115, name: "Ohropax", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 116, name: "Thymian", category: exampleCategories["Gewürze"]?.id, library: 1),
  ItemTemplate(id: 117, name: "Smoothie", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 118, name: "Buttergemüse", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 119, name: "Fuze Tea Pfirsich", category: exampleCategories["Getränke"]?.id, library: 1),
  ItemTemplate(id: 120, name: "Mezzo Mix", category: exampleCategories["Getränke"]?.id, library: 1),
  ItemTemplate(id: 121, name: "Süßkartoffel", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 122, name: "Strauchtomate", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 123, name: "Möhren", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 124, name: "Naturfrischkäse", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 125, name: "Wraps", category: exampleCategories["Backwaren"]?.id, library: 1),
  ItemTemplate(id: 126, name: "Pizzasoße/Knorr Kräuter", category: exampleCategories["Tomatenzeug"]?.id, library: 1),
  ItemTemplate(id: 127, name: "Basilikum, frisch", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 128, name: "Oregano, frisch", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 129, name: "Freitags TK", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 130, name: "German Allrounder", category: exampleCategories["Gewürze"]?.id, library: 1),
  ItemTemplate(id: 131, name: "Bitter Lemon", category: exampleCategories["Getränke"]?.id, library: 1),
  ItemTemplate(id: 132, name: "Orangensaft", category: exampleCategories["Getränke"]?.id, library: 1),
  ItemTemplate(id: 133, name: "H-Sahne", category: exampleCategories["MilchSahen"]?.id, library: 1),
  ItemTemplate(id: 134, name: "Suppengemüse", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 135, name: "Stückige Tomaten", category: exampleCategories["Tomatenzeug"]?.id, library: 1),
  ItemTemplate(id: 136, name: "Tortellini", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 137, name: "Mozzarella", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 138, name: "Salatmayonnaise", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 139, name: "Gurke", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 140, name: "Sandwichbrot", category: exampleCategories["Backwaren"]?.id, library: 1),
  ItemTemplate(id: 141, name: "Tomaten, groß", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 142, name: "Shampoo (Bekka)", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 143, name: "Zutaten für Sandwich", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 144, name: "Gehackte Tomaten", category: exampleCategories["Tomatenzeug"]?.id, library: 1),
  ItemTemplate(id: 145, name: "Porree", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 146, name: "Kichererbsen", category: exampleCategories["Konserven"]?.id, library: 1),
  ItemTemplate(id: 147, name: "Spinat", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 148, name: "Hygienespüler", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 149, name: "Kondome", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 150, name: "Tomatenmark", category: exampleCategories["Tomatenzeug"]?.id, library: 1),
  ItemTemplate(id: 151, name: "Zucchini", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 152, name: "Gnocchi", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 153, name: "Pringles Classic", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 154, name: "Udon-Nudeln", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 155, name: "Teriyakisoße", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 156, name: "Schmelzkäse", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 157, name: "Swiffer", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 158, name: "veganer Speck", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 159, name: "Zahnzwischenraumbürtschen", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 160, name: "veganes Hack", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 161, name: "Mais", category: exampleCategories["Konserven"]?.id, library: 1),
  ItemTemplate(id: 162, name: "Kidneybohnen", category: exampleCategories["Konserven"]?.id, library: 1),
  ItemTemplate(id: 163, name: "Brot", category: exampleCategories["Backwaren"]?.id, library: 1),
  ItemTemplate(id: 164, name: "Rahmgemüse", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 165, name: "Spülmittel", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 166, name: "Cordon Bleu (vegetarisch)", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 167, name: "Pommes", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 168, name: "Zuckerschoten", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 169, name: "Edelstahlreiniger", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 170, name: "Müsliriegel mit Schoko", category: exampleCategories["Trockenprodukte"]?.id, library: 1),
  ItemTemplate(id: 171, name: "Apfelmus", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 172, name: "Quark", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 173, name: "Gemüsebrühe", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 174, name: "Cranberries, getrocknet", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 175, name: "Birnendicksaft", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 176, name: "Magerquark", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 177, name: "Tomatensoße", category: exampleCategories["Tomatenzeug"]?.id, library: 1),
  ItemTemplate(id: 178, name: "Hähnchen-Ersatz", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 179, name: "Krabbensalat", category: exampleCategories["KühlthekeTeil1"]?.id, library: 1),
  ItemTemplate(id: 180, name: "Lappen", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 181, name: "Burgerbrötchen", category: exampleCategories["Backwaren"]?.id, library: 1),
  ItemTemplate(id: 182, name: "Pattys", category: exampleCategories["KühlthekeTeil1"]?.id, library: 1),
  ItemTemplate(id: 183, name: "Burgersoße", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 184, name: "Burgerdeko", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 185, name: "Weichspüler", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 186, name: "Taschentücher", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 187, name: "Zahnseide", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 188, name: "Essigreiniger", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 189, name: "Hot Dog Brötchen", category: exampleCategories["Backwaren"]?.id, library: 1),
  ItemTemplate(id: 190, name: "Würstchen", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 191, name: "Ketchup", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 192, name: "Hot Dog Gürckchen", category: exampleCategories["Konserven"]?.id, library: 1),
  ItemTemplate(id: 193, name: "Rostzwiebeln", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 194, name: "Gefrierbeutel", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 195, name: "Falafelteig", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 196, name: "Salat", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 197, name: "Naturjoghurt", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 198, name: "Spülbürste", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 199, name: "Pesto Verde", category: exampleCategories["Tomatenzeug"]?.id, library: 1),
  ItemTemplate(id: 200, name: "Tee", category: exampleCategories["Heißgetränke"]?.id, library: 1),
  ItemTemplate(id: 201, name: "Rösti", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 202, name: "Pilze", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 203, name: "Macaroni", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 204, name: "Scheuermilch", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 205, name: "Milchreis", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 206, name: "Kirchen", category: exampleCategories["Konserven"]?.id, library: 1),
  ItemTemplate(id: 207, name: "Fladenbrot", category: exampleCategories["Backwaren"]?.id, library: 1),
  ItemTemplate(id: 208, name: "Veganes Gyros", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 209, name: "Krautsalat", category: exampleCategories["KühlthekeTeil1"]?.id, library: 1),
  ItemTemplate(id: 210, name: "Mate", category: exampleCategories["Getränke"]?.id, library: 1),
  ItemTemplate(id: 211, name: "Müsli (auch für Alex)", category: exampleCategories["Trockenprodukte"]?.id, library: 1),
  ItemTemplate(id: 212, name: "Sojaschnetzel", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 213, name: "Schupfnudeln", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 214, name: "Sojacreme", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 215, name: "Bratwurst", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 216, name: "Roobios Vanille", category: exampleCategories["Heißgetränke"]?.id, library: 1),
  ItemTemplate(id: 217, name: "Senf", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 218, name: "Cannelloni", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 219, name: "Farfalle", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 220, name: "Früchtee/Blaubeertee", category: exampleCategories["Heißgetränke"]?.id, library: 1),
  ItemTemplate(id: 221, name: "Anginetten", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 222, name: "Fleischsalat", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 223, name: "Feine Leberwurst (ggf. mit Schnittlauch)", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 224, name: "Lebkuchen Bekka", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 225, name: "Funny Frisch Salz Chips", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 226, name: "Lippenpflege", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 227, name: "Honig", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
  ItemTemplate(id: 228, name: "Ofenkäse", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 229, name: "Kräuterbaguette", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 230, name: "Klöse", category: exampleCategories["Trockenprodukte"]?.id, library: 1),
  ItemTemplate(id: 231, name: "Maultaschen", category: exampleCategories["FrischeTheke"]?.id, library: 1),
  ItemTemplate(id: 232, name: "Pfannengemüse", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 233, name: "Tomatenfrischkäse", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 234, name: "Bio Mülltüten", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 235, name: "Salzstangen", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 236, name: "Birnen", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 237, name: "Knoppersriegel", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 238, name: "Joghurette", category: exampleCategories["Snacks"]?.id, library: 1),
  ItemTemplate(id: 239, name: "Rahm Kohlrabi", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 240, name: "Spätzle", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 241, name: "Kaisergemüse", category: exampleCategories["Tiefkühl"]?.id, library: 1),
  ItemTemplate(id: 242, name: "Tomatensalz (Just Spices)", category: exampleCategories["Gewürze"]?.id, library: 1),
  ItemTemplate(id: 243, name: "Kiwi 🥝", category: exampleCategories["ObstGemüse"]?.id, library: 1),
  ItemTemplate(id: 244, name: "Kinder Bueno", category: exampleCategories["Backzutaten"]?.id, library: 1),
  ItemTemplate(id: 245, name: "Binden", category: exampleCategories["Drogerie"]?.id, library: 1),
  ItemTemplate(id: 246, name: "Geschirrspülpulver", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 247, name: "Klarspüler", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 248, name: "Geschirrspülsalz", category: exampleCategories["Haushalt"]?.id, library: 1),
  ItemTemplate(id: 249, name: "Reisnudeln", category: exampleCategories["Teigwaren"]?.id, library: 1),
  ItemTemplate(id: 250, name: "Kräuterquark", category: exampleCategories["KühlthekeTeil2"]?.id, library: 1),
  ItemTemplate(id: 251, name: "Schnitzel", category: exampleCategories["Vegan"]?.id, library: 1),
  ItemTemplate(id: 252, name: "Päckchen Soße", category: exampleCategories["Vorratsschrank"]?.id, library: 1),
];

Future<void> seedDatabaseWithExampleData(AppDatabase db) async {
  await db.batch((batch) {
    batch.insertAll(db.itemCategories, exampleCategories.values);
    batch.insertAll(db.itemUnits, exampleUnits.values);
    batch.insertAll(db.templateLibraries, exampleLibraries.values);
    batch.insertAll(db.variantKeys, exampleVariantKeys.values);
    batch.insertAll(db.sortRules, exampleSortRules.values);
    batch.insertAll(db.sortOrders, exampleSortOrdersRuleOne);
    batch.insertAll(db.itemTemplates, exampleItemTemplates);
  });
}
