# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build release APK"
  lane :build_release do
    sh("flutter build apk --release")
  end

  desc "Build local release APK"
  lane :build_local_release do
    sh("flutter build apk --release --dart-define-from-file=./.env/prod.json")
  end

  desc "Build debug APK"
  lane :build_debug do
    sh("flutter build apk --debug --dart-define-from-file=./.env/dev.json")
  end

  desc "Build testing APK"
  lane :build_qa do
    sh("flutter build apk --release --dart-define-from-file=./.env/qa.json")
  end
end